import Head from "next/head";
import { useCallback, useState } from "react";
import { Inter } from "next/font/google";
import styles from "./index.module.css";
import { Todo } from "./api/todo";
import TodoList from "./+top/fragments/todo/list/TodoList";
import TodoCreator from "./+top/fragments/todo/create/TodoCreator";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [todoList, setTodoList] = useState<Todo[]>([]);

  const createTodo = useCallback((todo: Todo) => {
    // 配列の末尾に todo を追加している（push と同じような処理）
    setTodoList((prev) => [...prev, todo]);
  }, []);

  const removeTodo = useCallback((todo: Todo) => {
    setTodoList((prev) => prev.filter((t) => todo !== t));
  }, []);

  return (
    <>
      <Head>
        <title>TODO LIST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1 className={styles.title}>✔️ TODAY’S TODO LIST ✔️</h1>
          <TodoCreator onCreate={createTodo} />
          <TodoList todoList={todoList} onRemove={removeTodo} />
          <div></div>
        </div>
      </main>
    </>
  );
}
